module:
  imports:
    - path: github.com/CaiJimmy/hugo-theme-stack/v3
      disable: false

# config for blog

baseurl: https://toladev.netlify.app/
languageCode: en-us
paginate: 5
title: Tớ là Đép

# GA Tracking ID
googleAnalytics:

permalinks:
  post: /p/:slug/
  page: /:slug/

params:
  mainSections:
    - posts
  featuredImageField: image
  rssFullContent: true
  favicon: favicon.ico

  footer:
    since: 2022
    customText:

  dateFormat:
    published: Jan 02, 2006
    lastUpdated: Jan 02, 2006 15:04 MST

  sidebar:
    emoji: 🍥
    subtitle: Một gã tào lao, vẽ vớ vẩn, code lung tung, đi tùm lum.
    avatar:
      enabled: true
      local: true
      src: logo/logo.png

  article:
    math: false
    toc: true
    readingTime: true
    license:
      enabled: true
      default: Licensed under CC BY-NC-SA 4.0

  widgets:
    homepage:
      - type: search
      - type: archives
        params:
          limit: 5
      - type: categories
        params:
          limit: 10
      - type: tag-cloud
        params:
          limit: 10
    page:
      - type: toc

  colorScheme:
    # Display toggle
    toggle: true

    # Available values: auto, light, dark
    default: dark
